[wykoplinux]
title = "Wykop #linux"
url = "https://www.wykop.pl/tag/znaleziska/linux/wszystkie/"
entrySelector = "li.link > div > div > div"
titleSelector = "li.link > div > div > h2"
linkSelector = "li.link > div > div > h2 > a"
